name: kineticsz
channels:
  - bccp
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - astropy=4.0.1.post1=py37h7b6447c_1
  - attrs=19.3.0=py_0
  - backcall=0.2.0=py_0
  - beautifulsoup4=4.9.1=py37_0
  - bigfile=0.1.49=py37hb3ffb1f_7
  - blas=1.0=mkl
  - bleach=3.1.5=py_0
  - bokeh=2.1.0=py37_0
  - brotlipy=0.7.0=py37h7b6447c_1000
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.1.1=0
  - cachey=0.2.1=py37_0
  - certifi=2020.4.5.2=py37_0
  - cffi=1.14.0=py37he30daa8_1
  - chardet=3.0.4=py37_1003
  - classylss=0.2.9=py37ha5dfbcb_7
  - click=7.1.2=py_0
  - cloudpickle=1.4.1=py_0
  - corrfunc=2.3.0=py37hb3ffb1f_10
  - coverage=5.0=py37h7b6447c_0
  - cryptography=2.9.2=py37h1ba5d50_0
  - cycler=0.10.0=py37_0
  - cython=0.29.20=py37he6710b0_0
  - cytoolz=0.10.1=py37h7b6447c_0
  - dask=2.18.1=py_0
  - dask-core=2.18.1=py_0
  - dbus=1.13.14=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - distributed=2.18.0=py37_0
  - entrypoints=0.3=py37_0
  - expat=2.2.6=he6710b0_0
  - fire=0.3.1=pyh9f0ad1d_0
  - fitsio=1.1.2=py37hb3ffb1f_5
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fsspec=0.7.4=py_0
  - future=0.18.2=py37_1
  - glib=2.63.1=h3eb4bd4_1
  - gmp=6.1.2=h6c8ec71_1
  - gsl=2.4=h14c3975_4
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - h5py=2.10.0=py37h7918eee_0
  - halotools=0.7=py37h1211aff_5
  - hdf5=1.10.4=hb1b8bf9_0
  - heapdict=1.0.1=py_0
  - icu=58.2=he6710b0_3
  - idna=2.9=py_1
  - importlib-metadata=1.6.1=py37_0
  - importlib_metadata=1.6.1=0
  - intel-openmp=2020.1=217
  - ipykernel=5.3.0=py37h5ca1d4c_0
  - ipython=7.15.0=py37_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.17.0=py37_0
  - jinja2=2.11.2=py_0
  - jpeg=9b=h024ee3a_2
  - json5=0.9.5=py_0
  - jsonschema=3.2.0=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.3=py_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.3=py37_0
  - jupyterlab=2.1.4=py_1
  - jupyterlab_server=1.1.5=py_0
  - kdcount=0.3.29=py37hb3ffb1f_5
  - kiwisolver=1.2.0=py37hfd86e86_0
  - krb5=1.17.1=h173b8e3_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libcurl=7.69.1=h20c2e04_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.10=he19cac6_1
  - locket=0.2.0=py37_1
  - loguru=0.5.0=py37hc8dfbb8_0
  - lz4-c=1.9.2=he6710b0_0
  - markupsafe=1.1.1=py37h7b6447c_0
  - matplotlib=3.2.1=0
  - matplotlib-base=3.2.1=py37hef1b27d_0
  - mcfit=0.0.16=py37h5ca1d4c_1
  - mistune=0.8.4=py37h7b6447c_0
  - mkl=2020.1=217
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.1.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - more-itertools=8.4.0=py_0
  - mpi=1.0=mpich
  - mpi4py=3.0.3=py37h028fd6f_0
  - mpich=3.3.2=hc856adb_0
  - mpmath=1.1.0=py37_0
  - mpsort=0.1.17=py37he0e0d13_9
  - msgpack-python=1.0.0=py37hfd86e86_1
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.7=py_0
  - nbodykit=0.3.13=py37h5ca1d4c_6
  - ncurses=6.2=he6710b0_1
  - notebook=6.0.3=py37_0
  - numexpr=2.7.1=py37h423224d_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - olefile=0.46=py37_0
  - openssl=1.1.1g=h7b6447c_0
  - packaging=20.4=py_0
  - pandas=1.0.4=py37h0573a6f_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.7.0=py_0
  - partd=1.1.0=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.8.0=py37_0
  - pfft-python=0.1.21=py37he0e0d13_10
  - pickleshare=0.7.5=py37_0
  - pillow=7.1.2=py37hb39fc2d_0
  - pip=20.1.1=py37_1
  - plotly=4.8.1=py_0
  - pluggy=0.13.1=py37_0
  - pmesh=0.1.55=py37hb3ffb1f_5
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.5=py_0
  - prompt_toolkit=3.0.5=0
  - psutil=5.7.0=py37h7b6447c_0
  - ptyprocess=0.6.0=py37_0
  - py=1.8.2=py_0
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.16.0=py37h7b6447c_0
  - pysocks=1.7.1=py37_0
  - pytest=5.4.3=py37_0
  - python=3.7.7=hcff3b4d_5
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=py_0
  - pyyaml=5.3.1=py37h7b6447c_0
  - pyzmq=18.1.1=py37he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.7.4=py_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h7b6447c_0
  - requests=2.23.0=py37_0
  - retrying=1.3.3=py37_2
  - runtests=0.0.28=py37_2
  - scipy=1.4.1=py37h0b6359f_0
  - send2trash=1.5.0=py37_0
  - setuptools=47.3.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.15.0=py_0
  - sortedcontainers=2.2.2=py_0
  - soupsieve=2.0.1=py_0
  - sqlite=3.31.1=h62c20be_1
  - sympy=1.6=py37_0
  - tblib=1.6.0=py_0
  - termcolor=1.1.0=py37_1
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - tornado=6.0.4=py37h7b6447c_1
  - traitlets=4.3.3=py37_0
  - typing_extensions=3.7.4.1=py37_0
  - urllib3=1.25.9=py_0
  - wcwidth=0.2.4=py_0
  - webencodings=0.5.1=py37_1
  - wheel=0.34.2=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - wurlitzer=2.0.0=py37_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.1.7=had09818_2
  - zeromq=4.3.1=he6710b0_3
  - zict=2.0.0=py_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h0b5b093_3
  - pip:
    - arviz==0.8.3
    - camb==1.1.3
    - cftime==1.1.3
    - colorama==0.4.3
    - commonmark==0.9.1
    - dill==0.3.1.1
    - dropbox==10.2.0
    - emcee==3.0.2
    - getdist==1.1.2
    - joblib==0.15.1
    - multiprocess==0.70.9
    - netcdf4==1.5.3
    - pprintpp==0.4.0
    - python-box==4.2.3
    - rich==1.3.1
    - ruamel-yaml==0.16.10
    - ruamel-yaml-clib==0.2.0
    - scienceplots==1.0.3
    - toml==0.10.1
    - tqdm==4.46.0
    - xarray==0.15.1
prefix: /home/ugiri/anaconda3/envs/kineticsz

